[package]
name = "bullbitcoin-rnd"
authors = ["i5hi <ishi@satoshiportal.com>"]
version = "0.2.0"
edition = "2021"

[lib]
name = "bullwallet"
path = "src/lib.rs"
doctest = false
crate-type = ["staticlib", "cdylib", "rlib"] 

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[build]
profiler = true

[dependencies]
sha-1 = "0.10.0"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.0"
serde_json = "1.0"
rand_core = {version = "0.6.4", features = ["getrandom"]}
dotenv = "0.15.0"
ureq = "2.8.0"

bip39 = "1.0.0-rc1"
secp256k1 = {version = "0.27.0", features = ["rand", "global-context", "rand-std"]}
bitcoin = {version = "0.30.0", features = ["rand", "base64"]}
lightning-invoice = "0.26.0"
elements = { version = "0.20.0", features = ["serde"] }
electrum-client = "0.18.0"

bewallet = { git = "https://github.com/LeoComandini/BEWallet.git" }


