[package]
name = "boltz-client"
authors = ["i5hi <ishi@satoshiportal.com>"]
version = "0.3.1"
edition = "2021"

[lib]
name = "boltz_client"
path = "src/lib.rs"
doctest = false
crate-type = ["lib"] 

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[build]
profiler = true

[dependencies]
hex = "0.4.3"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
rand_core = {version = "0.6.4", features = ["getrandom"]}
ureq = {version = "2.8.0", features = ["json"]}
bip39 = "1.0.0-rc1"
electrum-client = "0.18.0"
bitcoin = {version = "0.30.0", features = ["rand", "base64", "rand-std"]}
elements = { git = "https://github.com/i5hi/rust-elements", features = ["serde"] }
lightning-invoice = "0.26.0"
